# filepath: c:\Users\PC\Desktop\rasa_chat_flight_hotel-booking\config\api_config.py
RAPIDAPI_KEY = "your_rapidapi_key_here"
API_HOST = "your_api_host_here"
CITY_MAPPING = {
    'الرباط': 'RBA',
    'الدار البيضاء': 'CMN',
    'مراكش': 'RAK',
    'فاس': 'FEZ',
    'أكادير': 'AGA',
    'طنجة': 'TNG',
    'وجدة': 'OUD',
    'الناظور': 'NDR',
    'العيون': 'EUN',
    'الداخلة': 'VIL',
    'باريس': 'PAR',
    'لندن': 'LON',
    'مدريد': 'MAD',
    'روما': 'ROM',
    'برشلونة': 'BCN',
    'فرانكفورت': 'FRA',
    'امستردام': 'AMS',
    'بروكسل': 'BRU',
    'جنيف': 'GVA',
    'زيورخ': 'ZRH',
    'فيينا': 'VIE',
    'اسطنبول': 'IST',
    'دبي': 'DXB',
    'أبو ظبي': 'AUH',
    'الدوحة': 'DOH',
    'القاهرة': 'CAI',
    'جدة': 'JED',
    'الرياض': 'RUH',
    'الكويت': 'KWI',
    'بيروت': 'BEY',
    'تونس': 'TUN',
    'الجزائر': 'ALG',
    'نيويورك': 'NYC',
    'لوس أنجلوس': 'LAX',
    'شيكاغو': 'CHI',
    'ميامي': 'MIA',
    'هونغ كونغ': 'HKG',
    'سنغافورة': 'SIN',
    'بانكوك': 'BKK',
    'طوكيو': 'TYO',
    'سيدني': 'SYD'
}